### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by 12345k** [12345k/flames_game#2]
Make a share button to share in a social network like facebook, twitter.

**Comment by DeusVultSVK** [comment]
Can i make this ?

**Comment by 12345k** [comment]
Yaa u can

**Comment by ani4aniket** [comment]
I m going to do this.

**Comment by ani4aniket** [comment]
I have fixed share button . Please rate my work.

**Comment by sahilgenius1** [comment]
can i make this?

**Comment by 12345k** [comment]
Yaa U can contribute in otherway but adding style or your own feature like
animation or quote depend upon the result
